export const currentAffairsFacts: [string, string][] = [
  ['Nigeria was admitted as a BRICS partner country in January 2025', 'BRICS'],
  ["Nigeria's four major tax reform laws were signed in June 2025", 'June 2025'],
  ["Nigeria's national minimum wage signed in 2024 was", '₦70,000'],
  ["Nigeria's national anthem was changed back in 2024 to", 'Nigeria, We Hail Thee'],
  ['The Dangote Refinery began production in Nigeria in', 'January 2024'],
  ["Nigeria's president in 2026 is", 'Bola Ahmed Tinubu'],
  ["Nigeria's vice president in 2026 is", 'Kashim Shettima'],
  ["Nigeria's Senate President in 2026 is", 'Godswill Akpabio'],
  ["Nigeria's House Speaker in 2026 is", 'Tajudeen Abbas'],
  ["Nigeria's Chief Justice in 2026 is", 'Kudirat Kekere-Ekun'],
  ["Nigeria's INEC chairman in 2026 is", 'Joash Amupitan'],
  ["Nigeria's central bank governor in 2026 is", 'Olayemi Cardoso'],
  ["Nigeria's Inspector-General of Police in 2026 is", 'Tunji Disu'],
  ['The country that won the 2025 Africa Cup of Nations was', 'Senegal'],
  ['Senegal defeated which country in the AFCON 2025 final?', 'Morocco'],
  ["Who scored Senegal's winning goal in the AFCON 2025 final?", 'Pape Gueye'],
  ['Nigeria finished third at AFCON 2025 after beating', 'Egypt'],
  ['Nigeria defeated Mozambique 4–0 in the AFCON 2025 round of', '16'],
  ["Nigeria's AFCON 2025 semi-final opponent was", 'Morocco'],
  ['Morocco defeated Nigeria in the AFCON 2025 semi-final by', 'Penalties'],
  ['Spain won the 2026 FIFA World Cup by defeating', 'Argentina'],
  ['What was the score in the 2026 FIFA World Cup final?', '1–0'],
  ["Who scored Spain's extra-time winner in the 2026 World Cup final?", 'Ferran Torres'],
  ['The 2026 FIFA World Cup was hosted by the United States, Canada and', 'Mexico'],
  ['The 2026 FIFA World Cup featured how many teams?', '48'],
  ['The 2026 FIFA World Cup final was played at', 'New York New Jersey Stadium'],
  ["Spain's 2026 World Cup title was its", 'Second'],
  ['Who was Spain’s opponent in the 2026 World Cup final?', 'Argentina'],
  ['Fela Kuti was named a 2026 Grammy Lifetime Achievement Award', 'Honoree'],
  ['The 2026 Grammy Special Merit Awards ceremony was held in', 'January 2026'],
];
